fix cloudflare

diff --git a/cloudflared/template.yaml b/cloudflared/template.yaml
--- a/cloudflared/template.yaml
+++ b/cloudflared/template.yaml
@@ -8,61 +8,60 @@ prepare_env: |-
   dpkg -i cloudflared.deb
 
 start: |-
-  if [[ $CF_TOKEN == "quick" ]]; then
-      # Split EXPOSE_PORTS into an array using ':' as the delimiter
-      IFS=':' read -ra names <<< "$PORT_MAPPING"
-      IFS=':' read -ra ports <<< "$EXPOSE_PORTS"
+    if [[ $CF_TOKEN == "quick" ]]; then
+        # Split EXPOSE_PORTS into an array using ':' as the delimiter
+        IFS=':' read -ra names <<< "$PORT_MAPPING"
+        IFS=':' read -ra ports <<< "$EXPOSE_PORTS"
 
-      # Loop over the ports array
-      paste <(printf '%s\n' "${names[@]}") <(printf '%s\n' "${ports[@]}") | while IFS=$'\t' read -r name port; do
-          if [[ $port == "" ]]; then
-              continue
-          fi
-          metrics_port=$((port+1))
+        # Loop over the ports array
+        paste <(printf '%s\n' "${names[@]}") <(printf '%s\n' "${ports[@]}") | while IFS=$'\t' read -r name port; do
+            if [[ $port == "" ]]; then
+                continue
+            fi
+            metrics_port=$((port+1))
 
-          # Generate PID file and log file names using a different delimiter
-          pidfile="/tmp/cloudflared_${name}.pid"
-          logfile="/tmp/cloudflared_${name}.log"
-          hostfile="/tmp/cloudflared_${name}.host"
+            # Generate PID file and log file names using a different delimiter
+            pidfile="/tmp/cloudflared_${name}.pid"
+            logfile="/tmp/cloudflared_${name}.log"
+            hostfile="/tmp/cloudflared_${name}.host"
+            
+            # Check if tunnel is already running
+            if [[ -f $pidfile ]]; then
+                if kill -0 "$(cat $pidfile)"; then
+                    log "Cloudflared tunnel for $name is already running."
+                    continue
+                fi
+            fi
+            log "Starting cloudflared tunnel for $name"
+            # Start cloudflared tunnel in the background
+            nohup cloudflared tunnel --url http://localhost:${port} --metrics localhost:${metrics_port} --pidfile "$pidfile" > "$logfile" 2>&1 &
 
-          if [[ -f $pidfile ]]; then
-              pid=$(cat $pidfile)
-              # Only start the tunnel if the process is not running
-              if ps -p $pid -o pid,comm | grep -q $pid; then
-                  log "Starting cloudflared tunnel for $name"
-                  # Start cloudflared tunnel in the background
-                  nohup cloudflared tunnel --url http://localhost:${port} --metrics localhost:${metrics_port} --pidfile "$pidfile" > "$logfile" 2>&1 &
-
-                  # Wait for the tunnel to become available
-                  retries=0
-                  max_retries=10
-                  while true; do
-                      sleep 5
-                      response=$(curl http://localhost:${metrics_port}/quicktunnel || true)
-                      if [[ $? -eq 0 ]] && [[ "$(echo "$response" | jq -r '.hostname')" != "" ]]; then
-                          hostname=$(echo "$response" | jq -r '.hostname')
-                          echo $hostname > $hostfile
-                          send_to_discord "Cloudflared: Hostname is $hostname for $name"
-                          break
-                      fi
-                      retries=$((retries+1))
-                      if [[ $retries -ge $max_retries ]]; then
-                          log "Error: Failed to get response after $max_retries attempts"
-                          send_to_discord "Cloudflared: Failed to get response after $max_retries attempts"
-                          break
-                      fi
-                      echo "Failed to get response. Retrying in 5 seconds..."
-                      sleep 5
-                  done
-              else
-                  log "Cloudflared tunnel for $name is already running."
-              fi
-          fi
-      done
-  else
-      cloudflared service install "$CF_TOKEN"
-      log "Cloudflared: Running as a service"
-  fi
+            # Wait for the tunnel to become available
+            retries=0
+            max_retries=10
+            while true; do
+                sleep 5
+                response=$(curl http://localhost:${metrics_port}/quicktunnel || true)
+                if [[ $? -eq 0 ]] && [[ "$(echo "$response" | jq -r '.hostname')" != "" ]]; then
+                    hostname=$(echo "$response" | jq -r '.hostname')
+                    echo $hostname > $hostfile
+                    send_to_discord "Cloudflared: Hostname is $hostname for $name"
+                    break
+                fi
+                retries=$((retries+1))
+                if [[ $retries -ge $max_retries ]]; then
+                    log "Error: Failed to get response after $max_retries attempts"
+                    send_to_discord "Cloudflared: Failed to get response after $max_retries attempts"
+                    break
+                fi
+                echo "Failed to get response. Retrying in 5 seconds..."
+                sleep 5
+            done
+        done
+    else
+        cloudflared service install "$CF_TOKEN"
+        send_to_discord "Cloudflared: Running as a service"
+    fi
 
 custom_start: ""
 custom_reload: |-
